[workspace]
resolver = "2"
members = [
  "apps/desktop/src-tauri",
  "crates/nocterm-application",
  "crates/nocterm-domain",
  "crates/nocterm-infrastructure",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
rust-version = "1.94"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2" }
thiserror = "2"
